---
- hosts: all
  become: no
  tasks:
  - name: configure KODI
    copy:
      src: "{{ item }}"
      dest: "~/.{{ item }}"
      mode: 0644
      backup: yes
    with_items:
      - kodi/userdata/Lircmap.xml
      - kodi/userdata/LCD.xml
