---
- hosts: all
  become: yes
  tasks:
  - name: Add Team KODI stable repository
    apt_repository:
      repo='ppa:team-xbmc/ppa' state=present
  - name: Install KODI
    apt:
      pkg=kodi state=installed update_cache=true
