---
- hosts: all
  become: yes
  tasks:
  - name: Install read-edid
    apt:
      pkg=read-edid state=installed update_cache=false
  - name: Create TV's edid
    shell: "get-edid > /etc/X11/edid.bin"
  - name: Configure XOrg
    copy:
      src: "{{ item }}"
      dest: "/{{ item }}"
      mode: 0644
      backup: yes
    with_items:
      - etc/X11/xorg.conf
