#! /bin/bash -p
#
# VDR Imon LCD timer script
#
### BEGIN INIT INFO
# Provides:          Imon LCD timer
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Sets the internal IMON LCD timer
# Description:       Sets the internal IMON LCD timer
### END INIT INFO

case "$1" in
    start)
        ;;
    stop)
        /usr/local/bin/vdrtimer.sh
        ;;
    restart|force-reload)
        ;;
    status)
        ;;
    *)
        exit 1
        ;;
esac

exit 0
